src/Vjezba/Vjezba.Web/Models/Mock/Company.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Vjezba.Web.Models.Mock
{
    public class Company
    {
        [Key]
        public int ID { get; set; }

        [Required]
        [StringLength(100, MinimumLength = 5)]
        public string Name { get; set; }

        [Required(ErrorMessage = "Email je obvezno unijeti (nesto@nesto.com)")]
        public string Email { get; set; }

        public string Address { get; set; }

        [Range(-90, 90)]
        public decimal Latitude { get; set; }

        [Range(-180, 180)]
        public decimal Longitude { get; set; }

        public DateTime DateFrom { get; set; }

        [ForeignKey("City")]
        public int? CityID { get; set; }

        public virtual City City { get; set; }

        public virtual ICollection<CompanyContact> Contacts { get; set; }
    }

}

src/Vjezba/Vjezba.Web/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vjezba.Web.Models;
using Vjezba.Web.Models.Mock;

namespace Vjezba.Web.Controllers
{
    [RoutePrefix("komp")]
    public class CompanyController : Controller
    {
        public ActionResult Index(string query)
        {
            var dbContext = new CompaniesManagerDbContext();

            List<Company> model = dbContext.Companies.Include("City").ToList();

            dbContext.Dispose();

            return View(model);
        }

        [HttpPost]
        public ActionResult IndexAjax(CompanyFilterModel model)
        {
            var dbContext = new CompaniesManagerDbContext();

            var companiesQuery = dbContext.Companies.Include("City").ToList();

            dbContext.Dispose();

            if (!string.IsNullOrWhiteSpace(model.Name))
                companiesQuery = companiesQuery.Where(p => p.Name.Contains(model.Name)).ToList();

            if (!string.IsNullOrWhiteSpace(model.Address))
                companiesQuery = companiesQuery.Where(p => p.Address.Contains(model.Address)).ToList();

            if (!string.IsNullOrWhiteSpace(model.Email))
                companiesQuery = companiesQuery.Where(p => p.Email.Contains(model.Email)).ToList();

            if (!string.IsNullOrWhiteSpace(model.CityName))
                companiesQuery = companiesQuery.Where(p => p.City.Name.Contains(model.CityName)).ToList();

            var data = companiesQuery.OrderBy(p => p.ID).ToList();

            //Iskoristit ćemo postojeći view Index. Potrebno je eksplicitno reći koji view želimo renderirati
            //jer se inače pokušava pronaći template AdvancedSearch.cshtml
            return PartialView("_IndexTable", data);
        }

        public ActionResult Create()
        {
            this.FillDropDownValues();
            return View();
        }

        [HttpPost]
        public ActionResult Create(Company model)
        {
            if (ModelState.IsValid)
            {
 
                var dbContext = new CompaniesManagerDbContext();

                dbContext.Companies.Add(model);
                dbContext.SaveChanges();
                dbContext.Dispose();

                return RedirectToAction("Index");
            }
            else
            {
                this.FillDropDownValues();
                return View(model);
            }
        }

        public ActionResult Edit(int id)
        {
            this.FillDropDownValues();

            var dbContext = new CompaniesManagerDbContext();

            var model = dbContext.Companies.Find(id);

            dbContext.Dispose();

            return View(model);
        }

        [HttpPost]
        [ActionName("Edit")]
        public ActionResult EditPost(int id)
        {
            var dbContext = new CompaniesManagerDbContext();
            var model = dbContext.Companies.Find(id);
            var didUpdateModelSucceed = this.TryUpdateModel(model);

            if (didUpdateModelSucceed && ModelState.IsValid)
            {
                dbContext.SaveChanges();
                dbContext.Dispose();
                return RedirectToAction("Index");
            }

            dbContext.Dispose();

            this.FillDropDownValues();

            return View(model);
        }

        public ActionResult Details(int? id = null)
        {
            if (id == null)return View();

            var dbContext = new CompaniesManagerDbContext();

            var model = dbContext.Companies.Where(comp => comp.ID == id).FirstOrDefault();

            return View(model);
        }

        [HttpPost]
        public JsonResult Delete(int? id = 0)
        {
            var dbContext = new CompaniesManagerDbContext();

            if (id == 0) return Json("Failed");

            var Company = dbContext.Companies.Find(id);

            dbContext.Entry(Company).State = System.Data.Entity.EntityState.Deleted;
            dbContext.SaveChanges();

            return Json("Success");
        }


        private void FillDropDownValues()
        {
            var dbContext = new CompaniesManagerDbContext();

            var possibleCities = dbContext.Cities.ToList();

            var selectItems = new List<SelectListItem>();

            dbContext.Dispose();

            //Polje je opcionalno
            var listItem = new SelectListItem();
            listItem.Text = "- odaberite -";
            listItem.Value = "";
            selectItems.Add(listItem);

            foreach (var city in possibleCities)
            {
                listItem = new SelectListItem();
                listItem.Text = city.Name;
                listItem.Value = city.ID.ToString();
                listItem.Selected = false;
                selectItems.Add(listItem);
            }
            ViewBag.PossibleCities = selectItems;
        }

        /*
         * 
        [Route("pretraga/{q:alpha:length(2,5)}")]
        public ActionResult Search(string q)
        {
            //Kada se bude radilo s bazom podataka, ova metoda još neće "otići" u bazu po podatke
            var query = MockCompanyRepository.GetInstance().All();

            if (!string.IsNullOrWhiteSpace(q))
                query = query.Where(p => p.Name.Contains(q));

            //Kada se bude radilo s bazom podataka, tek ova metoda bi generirala ispravni SQL i izvršila upit na bazi
            //te vratila samo potrebne rezultate
            var model = query.ToList();

            return View("Index", model);
        }

        */
    }
}

src/Vjezba/Vjezba.Web/Views/Company/Create.cshtml
﻿@model Vjezba.Web.Models.Mock.Company
@{
    ViewBag.Title = "Create new company";
}
<ol class="breadcrumb">
    <li>@Html.ActionLink("Home", "Index", "Home")</li>
    <li>@Html.ActionLink("Pregled kompanija", "Index")</li>
    <li class="active">Kreiranje nove kompanije</li>
</ol>
<h2>Create new company</h2>
@using (Html.BeginForm())
{
    <text>
        @Html.Partial("_CreateOrEdit")
    </text>

}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

src/Vjezba/Vjezba.Web/Views/Company/Details.cshtml
﻿﻿﻿@model Vjezba.Web.Models.Mock.Company
@{
    ViewBag.Title = "Detalji kompanije";
}
<ol class="breadcrumb">
    <li>@Html.ActionLink("Home", "Index", "Home")</li>
    <li>@Html.ActionLink("Pregled kompanija", "Index")</li>
    <li class="active">Detalji o kompaniji</li>
</ol>
<h2>Pregled detalja kompanije</h2>
@if (Model == null)
{
    <div class="alert alert-danger" role="alert">Ne postoji odabrana kompanija!</div>
}
else
{
    <table class="table table-condensed">
        <tbody>
            <tr>
                <th>ID</th>
                <td>@Model.ID</td>
            </tr>
            <tr>
                <th>Naziv</th>
                <td>@Model.Name</td>
            </tr>
            <tr>
                <th>Adresa</th>
                <td>@Model.Address</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>@Model.Email</td>
            </tr>
            <tr>
                <th>Grad</th>
                <td><a href="#" class="city-popover">@Model.City.Name</a></td>
            </tr>
            <tr>
                <td colspan="2">@Html.ActionLink("Uredi", "Edit", new { id = Model.ID })</td>
            </tr>
        </tbody>
    </table>
}
<div class="hidden" id="popover-data">
    @Html.Action("DetailsPartial", "City", new { id = Model.CityID, area = "Admin" })
</div>
@section scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            $(".city-popover").popover({ content: $("#popover-data").html(), html: true });
        });
    </script>

}

src/Vjezba/Vjezba.Web/Views/Company/Edit.cshtml
﻿﻿﻿@model Vjezba.Web.Models.Mock.Company

@{
    ViewBag.Title = "Create new company";
}

<ol class="breadcrumb">
    <li>@Html.ActionLink("Home", "Index", "Home")</li>
    <li>@Html.ActionLink("Pregled kompanija", "Index")</li>
    <li class="active">Uređivanje kompanije @Model.Name</li>
</ol>

<h2>Edit company data</h2>

@using (Html.BeginForm())
{

    <text>
        @Html.Partial("_CreateOrEdit")
        @Html.HiddenFor(p => p.ID)
    </text>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

src/Vjezba/Vjezba.Web/Views/Company/Index.cshtml
﻿﻿﻿@model List<Vjezba.Web.Models.Mock.Company>
@{
    ViewBag.Title = "Pregled kompanija";
}
<div class="panel panel-heading">
    <div class="row">
        <div class="col-xs-8">
            <h2>Pregled kompanija</h2>
        </div>
        <div class="col-xs-4 text-right">
            <a href="@Url.Action("Create")" style="margin-top: 20px;" class="btn btn-success">Dodaj novu kompaniju</a>
        </div>
    </div>
</div>

@Html.Partial("_CompanyFilter", new Vjezba.Web.Models.CompanyFilterModel())
@Html.Partial("_IndexTable", Model)

@section scripts{
    <style type="text/css">
        table.table tr.bold {
            font-weight: bold;
        }
    </style>
    <script type="text/javascript">

        $(function () {
            $(".companies-filter .submit-button").on("click", function () {
                $.ajax({
                    url: '@Url.Action("IndexAjax")',
                    method: "POST",
                    data: $(this).closest('form').serialize(),
                    success: function (data) {
                        $("#tbl-companies").replaceWith(data);
                        initFeatures();
                    }
                });
            });
            initFeatures();
        });

        function initFeatures() {
            $("tr").css("opacity", "0.9");
        }

        function setMaxOpacity(tableRow) {
            $(tableRow).css("opacity", "1");
        }

        function setLowOpacity(tr) {
            $(tr).css("opacity", "0.9");
        }

        function deleteAjax(compID) {
            $.ajax({
                url: '@Url.Action("Delete", "Company")',
                method: "POST",
                data: JSON.stringify({id : compID}),
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {
                    $("#" + compID).hide();
                    initFeatures();
                }
            });
            initFeatures();
        };

    </script>
}

src/Vjezba/Vjezba.Web/Views/Company/_CompanyFilter.cshtml
﻿﻿@model Vjezba.Web.Models.CompanyFilterModel
<div class="row">
    <div class="col-md-12">
        <form action="@Url.Action("Index")" method="post" class="form-inline companies-filter">
            <div class="form-group">
                @Html.EditorFor(p => p.Name, new { htmlAttributes = new { @class = "form-control", placeholder = "Pretraga po nazivu" } })
            </div>
            <div class="form-group">
                @Html.TextBoxFor(p => p.Address, new { @class = "form-control", placeholder = "Pretraga po adresi" })
            </div>
            <div class="form-group">
                <input type="text" class="form-control" name="@Html.NameFor(p => p.Email)" placeholder="Pretraga po e-mailu">
            </div>
            <div class="form-group">
                <input type="text" class="form-control" name="@Html.NameFor(p => p.CityName)" placeholder="Pretraga po gradu">
            </div>
            <button type="button" class="btn btn-default submit-button">Pretraga</button>
        </form>
    </div>
</div>

src/Vjezba/Vjezba.Web/Views/Company/_CreateOrEdit.cshtml
﻿@model Vjezba.Web.Models.Mock.Company
<div class="form-horizontal">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.DateFrom, new { @class = "col-md-2 control-label" })
        <div class="col-md-4">
            <div class="input-group date-picker">
                @Html.TextBoxFor(m => m.DateFrom, new { @class = "form-control" })
                <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
            </div>
            @Html.ValidationMessageFor(m => m.DateFrom, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Latitude, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Latitude, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Latitude, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Longitude, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Longitude, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Longitude, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.CityID, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(p => p.CityID, (IEnumerable<SelectListItem>)ViewBag.PossibleCities, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CityID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>

src/Vjezba/Vjezba.Web/Views/Company/_IndexTable.cshtml
﻿﻿﻿﻿@model List<Vjezba.Web.Models.Mock.Company>

<table id="tbl-companies" class="table table-condensed table-hover">
    <thead>
        <tr>
            <th>#</th>
            <th>Naziv</th>
            <th>Adresa</th>
            <th>Datum osnivanja</th>
            <th>Email</th>
            <th>Grad</th>
            <th>Akcija</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var company in Model)
        {
            <tr id="@company.ID" onmouseover="setMaxOpacity(this);" onmouseout="setLowOpacity(this);">
                <td>@company.ID</td>
                <td>@Html.ActionLink(company.Name, "Details", new { id = company.ID })</td>
                <td>@company.Address</td>
                <td>@company.DateFrom.ToShortDateString()</td>
                <td>@company.Email</td>
                @if (company.City != null)
                {
                    <td>@company.City.Name</td>
                }
                else
                {
                    <td>Nema grada</td>
                }
                <td>@Html.ActionLink("Uredi", "Edit", new { id = company.ID }) &nbsp;|&nbsp; <a href="#" onclick="deleteAjax(@company.ID)">Izbriši</a></td>
            </tr>
        }
    </tbody>
</table>